Develop (#4)
* init

* some

* Update api.v1.yaml

* Update version.yml

* Update version.yml

* Create .env

* Update version.yml

* Update api.v1.yaml

* Update .env

* Update version.yml

* Update version.yml

* Update version.yml

* Update .env

* Update .env

* patch

* Update version.yml

* Update version.yml

* Update api.v1.yaml

* Update version.yml

* Update .env

* Update version.yml

* Update version.yml

* Update version.yml

* Update version.yml

* Update version.yml

* Update version.yml

* Update version.yml

* Update .env

* Update version.yml

diff --git a/.github/workflows/version.yml b/.github/workflows/version.yml
--- a/.github/workflows/version.yml
+++ b/.github/workflows/version.yml
@@ -26,42 +26,42 @@ jobs:
           ref: main
           path: prod
       - name: Run OpenAPI Diff (from CURRENT revision)
+        continue-on-error: true
         uses: mvegter/openapi-diff-action@v0.23.3
         with:
           head-spec: current/reference/api.v1.yaml
           base-spec: prod/reference/api.v1.yaml
+        id: ref-check
       - name: Get PROD Version From .ENV
-        if: ${{ failure() }}
+        if: ${{ steps.ref-check.outcome }} == 'failure'
         uses: falti/dotenv-action@v0.2.5
         with:
           log-variables: true
           path: prod/.env
         id: prod-dotenv
-  check-env-version:
-    needs: [check-for-breaking-changes]
-    runs-on: ubuntu-latest
-    if: needs.check-for-breaking-changes.result == 'failure'
-    steps:
       - name: Bump release version
+        if: ${{ steps.ref-check.outcome }} == 'failure'
         id: bump_version
         uses: christian-draeger/increment-semantic-version@1.0.2
         with:
           current-version: ${{ steps.prod-dotenv.outputs.version }}
           version-fragment: 'major'
       - name: Get CURRENT Version From .ENV
-        
+        if: ${{ steps.ref-check.outcome }} == 'failure'
         uses: falti/dotenv-action@v0.2.5
         with:
           log-variables: true
           path: current/.env
         id: curr-dotenv
       - name: SEMVER STRING
-        
+        if: ${{ steps.ref-check.outcome }} == 'failure'
         uses: actions-ecosystem/action-regex-match@v2
         id: regex-match
         with:
           text: ${{ steps.curr-dotenv.outputs.version }}
           regex: '^([${{ steps.bump_version.outputs.next-version }}]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$'
-      - name: Version Is correct
+      - name: Version Is Not Correct
         if: ${{ steps.regex-match.outputs.match == '' }}
-        run: exit 1
+        run: |
+          echo "::error Version Should Be ${{ steps.bump_version.outputs.next-version }}"
+          exit 1
