Update version.yml

diff --git a/.github/workflows/version.yml b/.github/workflows/version.yml
--- a/.github/workflows/version.yml
+++ b/.github/workflows/version.yml
@@ -60,6 +60,8 @@ jobs:
         with:
           text: ${{ steps.curr-dotenv.outputs.version }}
           regex: '^([${{ steps.bump_version.outputs.next-version }}]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$'
-      - name: Version Is correct
+      - name: Version Is Not Correct
         if: ${{ steps.regex-match.outputs.match == '' }}
-        run: exit 1
+        run: |
+          echo "::error Version Should Be ${{ steps.bump_version.outputs.next-version }}"
+          exit 1
